"""empty message

Revision ID: 00f4754e0cab
Revises: 940ae84d76d1
Create Date: 2022-08-19 18:49:54.219690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f4754e0cab'
down_revision = '940ae84d76d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(), nullable=True))
    op.drop_column('shows', 'start_tim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_tim', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
