"""empty message

Revision ID: 179a5b7fd4cf
Revises: c4989fc8ef4e
Create Date: 2022-08-19 18:59:23.731686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '179a5b7fd4cf'
down_revision = 'c4989fc8ef4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'start_timee')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_timee', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
