"""empty message

Revision ID: c4989fc8ef4e
Revises: 00f4754e0cab
Create Date: 2022-08-19 18:59:08.835694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4989fc8ef4e'
down_revision = '00f4754e0cab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_timee', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_timee')
    # ### end Alembic commands ###
